### ISSUE TITLE
Missing Unicode 9.0 "Rolling on the floor laughing" and more

### ISSUE THREAD

**Issue by jhuckaby** [mathiasbynens/emoji-regex#10]
This otherwise wonderful and highly useful regular expression seems to be missing a number of modern / new Emoji included in [Unicode 9](http://emojipedia.org/unicode-9.0/) / [Emoji 3.0](http://emojipedia.org/emoji-3.0/).  The missing emojis include the popular [Rolling on the floor laughing](http://emojipedia.org/rolling-on-the-floor-laughing/) (:rofl:) and [Nauseated Face](http://emojipedia.org/nauseated-face/) (:nauseated_face:), as well as others.

<img width="192" alt="screenshot 2017-01-15 21 19 30" src="https://cloud.githubusercontent.com/assets/700765/21971743/5bd781ba-db68-11e6-9139-8241c8f95d50.png">

Any chance we can get these new ones added to the regex?

Thanks for an awesome library!

\- Joe

**Comment by jhuckaby** [comment]
Here's the link to the official list of all the new Emoji added to Unicode 9.0, from the unicode.org website:

http://www.unicode.org/emoji/charts/emoji-versions.html#v9.0_2016

🤣 🤤 🤠 🤡 🤥 🤢 🤧 🤶 🤴 🤵 🤰 🤦 🤦‍♂️ 🤦‍♀️ 🤷 🤷‍♂️ 🤷‍♀️ 🕺 🤺 🤸 🤸‍♂️ 🤸‍♀️ 🤼 🤼‍♂️ 🤼‍♀️ 🤽 🤽‍♂️ 🤽‍♀️ 🤾 🤾‍♂️ 🤾‍♀️ 🤹 🤹‍♂️ 🤹‍♀️ 🤳 🤞 🤙 🤛 🤜 🤚 🤝 🖤 🦍 🦊 🦌 🦏 🦇 🦅 🦆 🦉 🦎 🦈 🦐 🦑 🦋 🥀 🥝 🥑 🥔 🥕 🥒 🥜 🥐 🥖 🥞 🥓 🥙 🥚 🥘 🥗 🥛 🥂 🥃 🥄 🛴 🛵 🛑 🛶 🥇 🥈 🥉 🥊 🥋 🥅 🥁 🛒

**Comment by msklvsk** [comment]
…and also ❄️

**Comment by kesha-antonov** [comment]
🎈❤️

Missing these. Is there somewhere full list of emojis so I can update regex?

**Comment by khalifenizar** [comment]
I suspect the problem really lies with the [babel-plugin-transform-unicode-property-regex](https://github.com/mathiasbynens/babel-plugin-transform-unicode-property-regex) project, which is the Babel plugin that translates the Unicode property escapes in the regex to the actual code points of the emoji.

I took a look, but I don't really understand enough about how that works to incorporate the new emoji.

**Comment by patrickkettner** [comment]
The regex is genearted from the unicode escapes, via [babel-plugin-transform-unicode-property-regex](https://github.com/mathiasbynens/babel-plugin-transform-unicode-property-regex), which is powered by [regexpu-core](https://github.com/mathiasbynens/regexpu-core), which gets it's info from  [regenerate-unicode-properties](https://github.com/mathiasbynens/regenerate-unicode-properties). [The various emoji files](https://github.com/mathiasbynens/regenerate-unicode-properties/tree/master/Binary_Property) need to be updated to include the updates ranges for unicode 9 emoji

**Comment by patrickkettner** [comment]
PRed the upstream data, if and when that merges, just need to run the build script here.

**Comment by mxstbr** [comment]
Amazing, can't wait! Thanks @patrickkettner 🙏

**Comment by patrickkettner** [comment]
@mathiasbynens I assume that [src/index.js](https://github.com/mathiasbynens/emoji-regex/blob/624ad3ea65a958e1e713a4679045dfac01ce05ba/src/index.js) needs to be updated since the [change in Unicode-tr51](https://github.com/mathiasbynens/unicode-tr51/pull/3/files) created the new [Emoji_Component](https://github.com/patrickkettner/unicode-tr51/blob/75700214d78a217fbf22daec8e2194e07eccd9e4/Emoji_Component.js) file, but I am not sure where in that I would inject the values. Happy to create a PR if you could enlighten

**Comment by khalifenizar** [comment]
Should [index.js](https://github.com/mathiasbynens/emoji-regex/blob/master/index.js) also have been updated on commit af72086?

**Comment by patrickkettner** [comment]
@khalifenizar yeah, #12 for a fix. you can `require('emoji-regex/dist')` in the mean time

**Comment by mxstbr** [comment]
Amazing work, thanks so much for the quick update!
