### ISSUE TITLE
© is recognised as an emoji

### ISSUE THREAD

**Issue by Kilian** [mathiasbynens/emoji-regex#100]
The `©` character is recognised as an emoji. Is that correct?

**Comment by mathiasbynens** [comment]
The Unicode Standard designates it as an emoji. The following two sequences are matched:

U+00A9 → ©
U+00A9 U+FE0F → ©️

https://github.com/mathiasbynens/emoji-test-regex-pattern/blob/ab486bef950e17daa16da2a03db28f4574fe1557/dist/latest/index.txt#L25-L26

**Comment by Kilian** [comment]
Nevermind, this is discussed in #33
