### ISSUE TITLE
Is this lib basically doing /\p{Emoji}|\p{Default_Ignorable_Code_Point}/gu ?

### ISSUE THREAD

**Issue by caub** [mathiasbynens/emoji-regex#104]
That regex `/\p{Emoji}|\p{Default_Ignorable_Code_Point}/` would detect all emojis and join controls

**Comment by mathiasbynens** [comment]
> Is this lib basically doing `/\p{Emoji}|\p{Default_Ignorable_Code_Point}/gu`?

No.

`\p{Emoji}` only matches emoji consisting of a single code point. The vast majority of emoji consist of multiple code points.

We use https://github.com/mathiasbynens/emoji-test-regex-pattern.

**Comment by caub** [comment]
In my  usecase, I just need to remove them, so I can do `.replace(/\p{Emoji}|\p{Default_Ignorable_Code_Point}/gu, '')`, and that works for multi code points emojis is this right?

```
'️🤷‍♂️'.replace(/\p{Emoji}|\p{Default_Ignorable_Code_Point}/gu, '').length
0
```

but `.match(/\p{Emoji}|\p{Default_Ignorable_Code_Point}/gu)` return multiple characters instead of one, is this what you meant?

**Comment by mathiasbynens** [comment]
It might work for _some_ of them, but certainly not for all. Testing it against the full list in https://github.com/mathiasbynens/emoji-test-regex-pattern/blob/main/dist/latest/index-strings.txt, there are several failures.

```
// Note: `string` is the contents of the text file I pointed to.
string.replace(/\p{Emoji}|\p{Default_Ignorable_Code_Point}/gu, '').replaceAll('\n', '').length;
// -> 84
[...string.replace(/\p{Emoji}|\p{Default_Ignorable_Code_Point}/gu, '').replaceAll('\n', '')].length;
// -> 54
```
