### ISSUE TITLE
Question around choice of factory

### ISSUE THREAD

**Issue by mfbx9da4** [mathiasbynens/emoji-regex#105]
I noticed you've decided to use a factory pattern rather just a plain export. eg.

```javascript
export const emojiRegex = /[#*0-9]\uFE0F?\u20E3|[\xA9\xAE\u203C\u2049\u2122\u.....
```

Presumably this was decided because there is a cost to the JS runtime compiling the regex upfront which doesn't need to happen if it's contained in the function, this would only happen when the function is called? 

Would it make more sense to have a singleton API e.g

```javascript
let _regex
export const emojiRegex = () => {
   if (_regex === undefined) _regex = /[#*0-9]\uFE0F?\u20E3|[\xA9\xAE\u203C\u2049\u2122\u.....
  return _regex
}
```

 Or is the cost for compiling the regex only paid the first time the factory is called and subsequent calls are negligible?

**Comment by mathiasbynens** [comment]
Global RegExps are stateful through the `.lastIndex` property. Exporting a function that gives consumers a fresh RegExp means they don't have to worry about this.

Also see https://github.com/mathiasbynens/emoji-regex/issues/19#issuecomment-303298828
