### ISSUE TITLE
Determine emoji type?

### ISSUE THREAD

**Issue by GavanWilhite** [mathiasbynens/emoji-regex#106]
So unfortunately fluent emojis don't include country flags for "Microsoft reasons".

It would be amazing to be able to detect "country flag" emojis specifically. Any hope of being able to do this with emoji-regex?

**Comment by mathiasbynens** [comment]
This use case is a bit too specific for the emoji-regex project, which aims to match all emoji. 

Luckily, it's possible to do what you want with the new RegExp `v` flag in JavaScript. See the example here: https://v8.dev/features/regexp-v-flag#union:~:text=Another%20example%20is%20matching%20all%20commonly%2Dused%20flag%20emoji Babel supports transpiling it.

**Comment by GavanWilhite** [comment]
Ok, thanks!
