### ISSUE TITLE
Option of flagless search

### ISSUE THREAD

**Issue by roderickhsiao** [mathiasbynens/emoji-regex#19]
Hi Mathias,

We are currently having a use case that will run through array to check if the item is emoji

```javascript 
const emojiRegex = require('emoji-regex');
const textList = ['😁', '😂', '😃' ,'😄', '😅', '😆'];
const isEmoji = char => emojiRegex().text(char);
textList.forEach(char => every(isEmoji(char));
```

The global search state needs to be reset so we will need to call `emojiRegex` every time instead of just create once like.

```javascript 
const emojiRegex = require('emoji-regex');
const REGEX = emojiRegex();
const textList = ['😁', '😂', '😃' ,'😄', '😅', '😆'];
const isEmoji = char => REGEX.text(char);
textList.forEach(char => every(isEmoji(char));
```

probably really minor but there do have some perf difference if the use case is just to match single string.

https://jsperf.com/create-regex/1

Would like to hear about your idea and suggestion.

Thanks and Cheers!

**Comment by mathiasbynens** [comment]
Have you tried resetting `lastIndex` before using the regex?

```js
const isEmoji = (char) => {
  REGEX.lastIndex = 0;
  return REGEX.text(char);
};
```

**Comment by roderickhsiao** [comment]
good call ;) Didn't think about it.

Thanks greatly
