### ISSUE TITLE
Published version’s es2015 output is incorrect

### ISSUE THREAD

**Issue by ticky** [mathiasbynens/emoji-regex#24]
Hi there,

It looks like the release cut after #22 (v6.5.0) was merged perhaps didn’t have dependencies bumped correctly when it was built, as the es2015 modules don’t match the output I expected!

They should start with;

```js
module.exports = () => {
	// https://mathiasbynens.be/notes/es-unicode-property-escapes#emoji
	return (/\u{1F3F4}\u{E0067}\u{E0062}(?:\u{E0065}\u{E006E}\u{E0067}|\u{E0077}\u{E006C}\u{E0073}|\u{E0073}\u{E0063}\u{E0074})\u{E007F}|\u{1F469}\u200D\u{1F469}\u200D.../gu
	);
};
```

But instead begin;

```js

module.exports = () => {
	// https://mathiasbynens.be/notes/es-unicode-property-escapes#emoji
	return (/\uD83C\uDFF4\uDB40\uDC67\uDB40\uDC62(?:\uDB40\uDC65\uDB40\uDC6E\uDB40\uDC67|\uDB40\uDC77\uDB40\uDC6C\uDB40\uDC73|\uDB40\uDC73\uDB40\uDC63\uDB40\uDC74)\uDB40\uDC7F|\uD83D\uDC69\u200D\uD83D\uDC69\u200D(?:\uD83D\uDC66\u200D\uD83D\uDC66|\uD83D\uDC67\u200D(?:\uD83D[\uDC66\uDC67]))|…/gu
	);
};
```

Could you do a new release and double check the dependencies (regexgen in particular!) are up to date? Unfortunately there’s no spec checking the _format_ of the regex! 😅

**Comment by mathiasbynens** [comment]
Whoops! Should be fixed in v6.5.1.

Thanks for reporting!
