### ISSUE TITLE
Some emojis ending with `\ufe0f` are not completely matched

### ISSUE THREAD

**Issue by merih** [mathiasbynens/emoji-regex#28]
Male detective emoji, 🕵️ `"\u{1f575}\ufe0f"`, when matched with emoji regex, not all of its codepoints are consumed, leaving `\ufe0f` behind. The emoji is typed with control+cmd+space shortcut of Mac.

```
"\u{1f575}\ufe0f".match(emojiRegex(), "").length
//> 1
```

**Comment by mathiasbynens** [comment]
That’s not a standard emoji sequence — U+1F575 U+FE0F is not listed in [`emoji-zwj-sequences.txt`](http://unicode.org/Public/emoji/5.0/emoji-zwj-sequences.txt). The U+FE0F is not necessary. I don’t know why the macOS emoji picker appends it in this case, but it looks like a bug on Apple’s end.

**Comment by gilmoreorless** [comment]
Apple appears to have a very loose idea of conformance to the standard set of codepoints. While working on other fixes for `emoji-regex` I created a list of all the emoji available on my Mac (macOS 10.12.6) via the emoji picker. (Handy hint: Don't do that if you value your time and patience.)

There were 49 `Emoji_Presentation` or `Emoji_Modifier_Base` characters that have `U+FE0F` appended to them by the macOS picker, with no real consistency about which ones do or don't get the variation selector added (e.g. 🤞 doesn't but ✌️ does). Plus there were another 100 or so textual representation characters that are displayed by macOS in presentation mode _without_ appending `U+FE0F`.

**Comment by anoff** [comment]
Any real downsides to adding this control character to the regex? Besides bloating the regex just to workaround a possible MacOS bug.

**Comment by artyom** [comment]
Excerpt from <http://unicode.org/Public/emoji/5.0/emoji-test.txt>:

```
1F575 FE0F                                 ; fully-qualified     # 🕵️ detective
1F575                                      ; non-fully-qualified # 🕵 detective
```

So the sequence in question is rather conformant.

**Comment by mathiasbynens** [comment]
Thanks for the pointer, @artyom!

Per <http://unicode.org/reports/tr51/#Emoji_Implementation_Notes>, emoji ZWJ sequences “may have an emoji presentation selector”.

**Comment by mathiasbynens** [comment]
Hacky solution: just add `\uFE0F?` to the regex (or `[\uFE0E\uFE0F]?` for the `text` regex). However, some of the sequences already end with presentation or variation selectors and are therefore already qualified — those shouldn’t be matched along with the U+FE0F. A proper fix will take some more time.

**Comment by gilmoreorless** [comment]
For my [own project's use](https://gilmoreorless.github.io/emoji-censor/) I ended up going with that same hacky solution. I figured it wasn't right to submit a PR back to this project for it, so I just left it on a [custom branch of my fork](https://github.com/gilmoreorless/emoji-regex/compare/master...emoji-censor-variation).

**Comment by fredvollmer** [comment]
Are there any plans to integrate this into the project? It seems that the consensus is that this is a legitimate use case...sorry if I'm off base here

**Comment by mathiasbynens** [comment]
@fredvollmer https://github.com/mathiasbynens/emoji-regex/issues/28#issuecomment-323044429 answers your question. I’d welcome a patch :)

**Comment by jerry153fish** [comment]
Hi @mathiasbynens, is it possible to add rules for those not fall on the sequence

egs : 

`
🐿 🕊 👁 🕷 🕸 👓 ⛑ 🗣 🕶  ✌️ ☝️ ✍️ ✌🏼 ⚡️ ⭐️ 🌪 🌤 🌥 🌦 🌧 ⛈ 🌩 🌨 🌬 💨 🌶 🍽 ⛸ ⛷ 🎖 🏵 🎗 🎟 🏎 🏍 🛩 🛰 🛥 🛳 🗺 🏟 ⛱ 🏖 🏝 🏜 ⛰ 🏔 🏕 🏚 🏘 🏗 🏛 ⛩ 🛤 🛣 🏞 🏙 🖥 🖨 🖱 🖲 🕹 🗜 📽 🎞 🎙 🎚 🎛 ⏱ ⏲ 🕯 🗑 🛢
			// ⚒ 🛠 ⛏ ⛓ 🗡 🛡 🕳 🌡 🛎 🗝 🛋 🛏 🖼 🛍 🏷 🗒 🗓 🗃 🗳 🗄 🗂 🗞 🖇 🖊 🖋 🖌 🖍 🕉 ⏸ ⏯ ⏹ ⏺ ⏭ ⏮ 👁‍🗨 🗯 🕰 ⛴ 🌫 🀄 ⛄️ ⛅️ ☔️ ☕️ ⚽️ ⚾ ⛳️ ⛵️ ⛽️ ⚓️ ⛲️ ⛺️ ⛪️ ⌚️ ⌛️ ♈️ ♉️ ♊️ ♋️ ♌️ ♍️ ♎️ ♏️ ♐️ ♑️ ♒️ ♓️ 🈚️ ⭕️ ⛔️ ❗️ 🈯️  ♿️ ⚪️ ⚫️ ⬛️ ⬜️ ◾️ ◽️
`

**Comment by mathiasbynens** [comment]
Try again using the latest release!

```js
const emojiRegex = require('emoji-regex');

const string = '\u{1F575}\uFE0F'; // '🕵️'
console.log(
	string.match(emojiRegex())
);
// → [ '🕵️' ]
```

Closing as fixed. Feel free to reopen or file a new bug in case I missed anything.
