### ISSUE TITLE
browser compatibility

### ISSUE THREAD

**Issue by sido420** [mathiasbynens/emoji-regex#31]
Since the project specifically mentions nodejs so I wanted to confirm if this can be used on client side (ie. major desktop+mobile browsers).

My use case is to insert a space next to the character typed in by user as soon as they do that. Can this module help me with that or I'm on the wrong track?

**Comment by mathiasbynens** [comment]
> Since the project specifically mentions nodejs so I wanted to confirm if this can be used on client side (ie. major desktop+mobile browsers).

It’s just a regular expression. It works across the board.

> My use case is to insert a space next to the character typed in by user as soon as they do that. Can this module help me with that or I'm on the wrong track?

Insert a space after every emoji in a string?

```js
string.replace(emojiRegex(), `${$&} `);
```
