### ISSUE TITLE
🎖 is not matched

### ISSUE THREAD

**Issue by brekk** [mathiasbynens/emoji-regex#32]
Hey there,

Love this library, but I've been seeing some new(er) emojis that are not matched correctly?

```js
import emojiRegex from 'emoji-regex'
const e = emojiRegex()
e.test('🎖') // false
```

Thanks,

Brekk

**Comment by astoilkov** [comment]
I can add 🗡 to this issue.

**Comment by gilmoreorless** [comment]
Both of those are defined in the `Emoji` category but not the `Emoji_Presentation` category in [the Unicode source data](https://unicode.org/Public/emoji/11.0/emoji-data.txt). Technically they're meant to have different representations for "plain text" vs "emoji" modes, based on the presence or absence of the presentation selector `U+FE0F`. Unfortunately OSes are notoriously sloppy with adhering to that (see [#28 (comment)](https://github.com/mathiasbynens/emoji-regex/issues/28#issuecomment-321435043)), and the default regex is not matching the "plain text" variant.

Those characters are matched by the text version of emoji-regex, which ignores the presentation selector:

```js
const emojiRegex = require('emoji-regex')
emojiRegex().test('🎖')  // false

const emojiTextRegex = require('emoji-regex/text')
emojiTextRegex().test('🎖')  // true
```
