### ISSUE TITLE
Some emojis lost

### ISSUE THREAD

**Issue by mishelen** [mathiasbynens/emoji-regex#34]
I try to parse such string ♿️🎇🏖🌎🗺🍌🐯 , then I get array of emojis that when I join I get string of 13 symbols. When original emojis has 14 symbols. 

So after parsing was lost 'VARIATION SELECTOR-16' 

I used `text.js` for working with variations

**Comment by mathiasbynens** [comment]
Please post a working code example. I’m closing this issue until that happens. Thank you.
