### ISSUE TITLE
Handle 👁‍🗨

### ISSUE THREAD

**Issue by porada** [mathiasbynens/emoji-regex#4]
Looks like the script doesn’t match [the character](http://iwitnessbullying.org/how-to-use-the-eye) properly:

```js
'<p>Foo 👁‍🗨 Bar</p>'.replace(emojiRegex(), function(match) {
  return '<b>' + match + '</b>';
});

// → <p>Foo <b>👁</b>‍🗨 Bar</p>
```

**Comment by mathiasbynens** [comment]
This is:

1. U+1F441 EYE
2. U+200D ZERO WIDTH JOINER
3. U+1F5E8 LEFT SPEECH BUBBLE

Note that U+1F5E8 is not [in the list of emoji](https://github.com/mathiasbynens/unicode-tr51).

This repo is based on the Unicode standard though, and I’d rather not add exceptions to it based on non-standard extensions. Similar issue: https://github.com/mathiasbynens/emoji-regex/issues/2#issuecomment-118503456

For example, `👁‍🗨` only seems to get rendered as a single glyph on Apple’s operating systems. So whether you want to treat it as a single unit or not depends on the system you’re writing code for.

**Comment by porada** [comment]
Okay, that makes sense. Thanks. :v:
