### ISSUE TITLE
IE 10 IE 11 doesn't support this regex

### ISSUE THREAD

**Issue by NikolaySolodukhin** [mathiasbynens/emoji-regex#41]

**Comment by mathiasbynens** [comment]
What happens if you use it?

**Comment by NikolaySolodukhin** [comment]
Maybe I use this regex incorrectly? http://prntscr.com/kgohty I error Invalid range in character set

**Comment by NikolaySolodukhin** [comment]
I don't using babel that's why ie has crashed. Sorry
