### ISSUE TITLE
some emoji can't match

### ISSUE THREAD

**Issue by gdutwyg** [mathiasbynens/emoji-regex#44]
you can try `'\u263a'.match(regex)` and `'\u263a\ufe0f'.match(regex)`

result:

`'\u263a\ufe0f'` can match, but `'\u263a'` can‘t

**Comment by Chaptykov** [comment]
I found some emoji not matched with this regexp:

👁🗣⛑🕶🕷🕸🕊🌪🌥🌦🌧⛈🌩⛸⛷🎖🏵🎗🎟🏎🏍🛩🛥🛳⛱🏖🏝🏜⛰🏔🏘🏚🏗⛩🛤🛣🏞🖥🖨🖱🖲🕹🗜
📽🎞🎙🎚🎛⏱⏲🕯🗑🛢⚒🛠⛏⛓🗡🛡🕳🌡🛎🗝🛋🛏🖼 🛍🏷🗒 🗓🗃🗳🗄🗂🗞🖇🖊🖋🖌🖍⏸⏯⏹⏺⏭👁‍🗨♟♾

![image](https://user-images.githubusercontent.com/1920602/45104730-69bd4a80-b13b-11e8-90df-e30cfecb515f.png)

**Comment by Chaptykov** [comment]
@mathiasbynens Could you comment it, please?

**Comment by mpalmerlee** [comment]
I believe what you want is the text version of the regex that doesn't require the variation selector (U+FE0F)
e.g.:
`const emojiRegex = require('emoji-regex/text.js');`

**Comment by Chaptykov** [comment]
Looks like you are right. I think I should be more attentive. Thank you!

**Comment by mathiasbynens** [comment]
Closing, since OP meant to use the `/text.js` regex, and it addresses their problem.
