### ISSUE TITLE
Package name dependency

### ISSUE THREAD

**Issue by Ella77** [mathiasbynens/emoji-regex#49]
First, I want to thank you for great projects :)
I am using for emoji usage analysis!! 

There is a tiny problem when installing... because of same name of module and package ( emoji-regex)  ///

when I tried to install with "npm install emoji-regex"
code ENOSELF
npm ERR! Refusing to install package with name "emoji-regex" under a package
npm ERR! also called "emoji-regex". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR! 
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:

I write this because there is no issue regarding this.... 
Also For those who experiencing same problems :
When switching module (in package.json) into different name or project name(re-  git clone is easiest) , it can work.

Free to comment!

**Comment by Richienb** [comment]
That's how npm works. You can't install `emoji-regex` in `emoji-regex` because npm assumes that would create recursive dependencies.
