### ISSUE TITLE
Using regex to replace emoji characters

### ISSUE THREAD

**Issue by perry-mitchell** [mathiasbynens/emoji-regex#5]
When trying to use emoji-regex to replace certain characters, some data is left in the resulting string:

```
"❤️".replace(emojiRegex(), ' ').length; // 2
```

Although it will match, it doesn't appear to match the entire "string".

**Comment by mathiasbynens** [comment]
https://github.com/mathiasbynens/emoji-regex/issues/2#issuecomment-118503456
