### ISSUE TITLE
Not sure if this regex does what you want

### ISSUE THREAD

**Issue by LouisMichael** [mathiasbynens/emoji-regex#56]
I was looking through some project regex and found this one [here](https://github.com/mathiasbynens/emoji-regex/blob/9a61d5fa9d6180586a230522aad86d093925efae/src/text.js#L3). It seems to be trying to use \p{ to express a unicode value but this notation is not supported in the JS regex dialect and will most likely not behave as expected when interacting with the u flag.

**Comment by mathiasbynens** [comment]
> It seems to be trying to use `\p{` to express a unicode value but this notation is not supported in the JS regex dialect

It does: https://mathiasbynens.be/notes/es-unicode-property-escapes

The distributed version of this library is transpiled code that doesn’t use the `\p{}` notation (since it’s not yet supported in all modern browsers).

**Comment by binyamin** [comment]
> The distributed version of this library is transpiled code that doesn’t use the \p{} notation (since it’s not yet supported in all modern browsers).

@mathiasbynens It works in node v10.23.0 (the earliest support lts). Can there be a note on the readme, in case the use-case is only server-side?
