### ISSUE TITLE
add a regexp to just match emojis, complete emojis

### ISSUE THREAD

**Issue by titoBouzout** [mathiasbynens/emoji-regex#58]
@mathiasbynens could be possible please to have a regexp to just match emojis? for example 
0 is not 0️⃣
🐱‍👤 is 🐱‍👤
🐱‍👤 is not 🐱+👤
Thanks!

**Comment by mathiasbynens** [comment]
Sure — just don’t use the `text` version. See the README.

**Comment by titoBouzout** [comment]
It does not work mathias, it does return true, Im confused 
https://i.imgur.com/2Tud73Z.png

**Comment by titoBouzout** [comment]
I finally understand now why the ninjacat does not work https://blog.emojipedia.org/ninja-cat-the-windows-only-emoji/
