### ISSUE TITLE
does not match 👁 and 🕶 on MacOS Mojave

### ISSUE THREAD

**Issue by vijaiendransv** [mathiasbynens/emoji-regex#59]
Tested the regex expression using http://regex101.com/.  Can closeout if it is not an actual issue.

**Comment by 4ver** [comment]
See example here https://runkit.com/4ver/issue-with-emoji-regex-and-matching

**Comment by eramdam** [comment]
FWIW, in our app we have to detect emojis by splitting a given string using a regex. The following code helped working around the issue 

```js
import * as baseEmojiRegex from 'emoji-regex';

// emoji-regex doesn't match some emojis
// https://github.com/mathiasbynens/emoji-regex/issues/59
const rsSurrPair = '[\\ud800-\\udbff][\\udc00-\\udfff]';
const rsEmoji = `(?:${rsSurrPair})`;

export const emojiSplitRegexp = new RegExp(
  `(${baseEmojiRegex.default().source}|${rsEmoji}|:[\\w+-]+:(?::skin-tone-[2-6]:)?)`,
  'i'
);

```

I couldn't figure out how to make a version that works with the `.exec()` usage however.

**Comment by niftylettuce** [comment]
The package [emoji-patterns](https://github.com/tonton-pixel/emoji-patterns) is a great alternative and works rather well.

```sh
> const emojiPatterns = require ('emoji-patterns');
undefined
> const emojiAllRegex = new RegExp (emojiPatterns["Emoji_All"], 'gu');
undefined
> '🕹'.match(emojiAllRegex)
[ '🕹' ]
> 'does not match 👁 and 🕶 on MacOS Mojave'.match(emojiAllRegex)
[ '👁', '🕶' ]
```

**Comment by mathiasbynens** [comment]
Generally, the philosophy behind emoji-regex is to avoid making decisions about which characters/sequences are emoji and which aren't, and instead let the Unicode Standard make those decisions.

As long as these symbols are not official emoji, we don't want to match them.
