### ISSUE TITLE
does not match ⌫

### ISSUE THREAD

**Issue by coulonxyz** [mathiasbynens/emoji-regex#62]
the regex does not match this special character: https://www.compart.com/en/unicode/U+232B
Julien

**Comment by mathiasbynens** [comment]
⌫ is a text character (not an emoji) per the Unicode Standard, and it renders as such on most platforms, so I've decided not to include it in this library for now.

Generally, the philosophy behind emoji-regex is to avoid making decisions about which characters/sequences are emoji and which aren't, and instead let the Unicode Standard make those decisions.
