### ISSUE TITLE
How can I use this library to match all-emoji strings? i.e. strings consisting of emoji characters only

### ISSUE THREAD

**Issue by debajit** [mathiasbynens/emoji-regex#64]
I'm writing a chat-like application, and I need to check if a string consists only of Emoji characters, so that I could render the emoji in large text.

Currently I'm using a function like the following to do this:

```javascript
function isEmojiOnly(text, emojiRegex) {
  const textOnly = text.replace(/\s/g, "")
  return textOnly.replace(emojiRegex, "") === ""
}
```

- isEmojiOnly("Hello") -----> false
- isEmojiOnly("Hello 🙂") -----> false (since it also contains other non-emoji characters)
- isEmojiOnly("👍") -----> true
- isEmojiOnly("👍👏") -----> true

Does the emoji-regex library offer any provision to do this more optimally?

**Comment by mxstbr** [comment]
You have to mangle the regexp a bit, we did a similar thing for Spectrum. See the source here: https://github.com/withspectrum/spectrum/blob/alpha/shared/only-contains-emoji.js

Hope that helps!

**Comment by OlivierFreyssinet** [comment]
Did it like this:
```
// beginText ( (whitespace*)(emoji+)(whitespace*) )+ endText
emojiOnlyRegExp = new RegExp(`^(\\s*(${emojiRegex().source})+\\s*)+$`)
```
This solution matches strings that have only emojis and whitespaces, but doesn't match strings with only whitespace

**Comment by chmiiller** [comment]
This is very useful and yeah, would be nice to have it out of the box from the lib

**Comment by mathiasbynens** [comment]
Apply the regex and see if the match `===` the original string?

**Comment by mathiasbynens** [comment]
You could matchAllIf you only want to render the emoji in large text when the input consists of a single emoji (or single emoji sequence, i.e. visually a single glyph), then you could simply apply the regex and see if the match `===` the original string.

If you want to cover the case where the input consists of multiple, separate emoji (like in your `isEmojiOnly('👍👏')` example), you can get the `emojiRegex().source` and wrap it in `^` and `$` like @mxstbr showed.
