### ISSUE TITLE
Release an update for Unicode 12.1?

### ISSUE THREAD

**Issue by scriby** [mathiasbynens/emoji-regex#66]

**Comment by codex-zaydek** [comment]
@scriby If you look at the source, it looks like it’s already _on_ 12.1:

```js
const array = require(`unicode-12.1.0/Sequence_Property/${property}/index.js`);
```

https://github.com/mathiasbynens/emoji-regex/blob/master/script/get-sequences.js

**Comment by scriby** [comment]
Yes, it is on head, but it was never published to npm.

**Comment by codex-zaydek** [comment]
Ah, You should know that Unicode 13.0 was released *very* recently: https://unicode.org/Public/emoji/13.0/emoji-test.txt.

**Comment by TreeMan360** [comment]
Any chance we get get a unicode 13.0 release?

**Comment by ManuelFte** [comment]
This library seems to be abandoned. There have been no commits since May and there's an unapproved pull request from August. If someone knows of a fork or an alternative library that is up-to-date, please let me know.

**Comment by codex-zaydek** [comment]
I wouldn’t go as far as to say _abandoned_. Mathias (the author) works at Google, I’m sure he’s just busy with his other responsibilities.

That being said, I created my own solution to efficiently determine the next or previous emoji: https://github.com/codex-src/emoji-trie.js. It’s on Unicode 13.0 and I’m using it myself. You can create an issue there if you have questions or concerns about it.

**Comment by Amareis** [comment]
Hey-hey! @mathiasbynens can you please release unicode 13 update?

**Comment by mathiasbynens** [comment]
emoji-regex has been updated to use Unicode 13.0.0!

**Comment by Amareis** [comment]
Big thanks!
