### ISSUE TITLE
Doesn't match ☤ (Caduceus, U+2624)

### ISSUE THREAD

**Issue by josephrocca** [mathiasbynens/emoji-regex#67]
Just tested version 8 and it doesn't match ☤ (Caduceus, U+2624)

Demo: https://jsbin.com/hazotolexu/edit?html,output

```js
(async function() {
  window.module = {}
  eval( await fetch("https://unpkg.com/emoji-regex/index.js").then(r => r.text()) );
  emojiRegex = window.module.exports();
  alert( emojiRegex.test("☤") );
})();
```

It has been around since 1993, but note that emojipedia says:

> This Unicode character has no emoji version, meaning this is intended to display only as a black and white glyph on most platforms. It has not been Recommended For General Interchange (RGI) — as an emoji — by Unicode.

So perhaps you don't want to include it in this lib. Thought I'd mention it just in case. Thanks for the great lib in any case! Really saved the day for me :)

**Comment by nolanlawson** [comment]
It seems that 🕫 (bullhorn) also fits this description. Not matched by emoji-regex, and emojipedia has the same blurb about "no emoji version."

**Comment by josephrocca** [comment]
In case it's helpful to others, I ended up creating making a module that fixes this and also incorporates @gilmoreorless's variation selector fix: https://github.com/josephrocca/emoji-and-symbol-regex

**Comment by ChurchTao** [comment]
@josephrocca  thank you for your https://github.com/josephrocca/emoji-and-symbol-regex, but regex not very readable, try my edition base on https://www.unicode.org/Public/emoji/13.0/emoji-test.txt

**Comment by mathiasbynens** [comment]
Thanks for reporting this, @josephrocca! As you mention, ☤ is a text character per the Unicode Standard, and it renders as such on most platforms, so I've decided not to include it in this library for now. Generally, I want to avoid making decisions about which characters/sequences are emoji and which aren't, and instead let the Unicode Standard make those decisions.
