### ISSUE TITLE
Bug: The regex in text.js and index.js are the same?

### ISSUE THREAD

**Issue by junjizhi** [mathiasbynens/emoji-regex#69]
https://github.com/mathiasbynens/emoji-regex/blob/master/src/index.js:

```javascript
/<% emojiSequence %>|\p{Emoji_Presentation}|\p{Emoji}\uFE0F|\p{Emoji_Modifier_Base}/gu;
```

https://github.com/mathiasbynens/emoji-regex/blob/master/src/text.js:
```javascript
/<% emojiSequence %>|\p{Emoji_Presentation}|\p{Emoji}\uFE0F?|\p{Emoji_Modifier_Base}/gu;
```

Notice it is missing a `?` in the first regex besides `\uFE0F`

**Comment by mathiasbynens** [comment]
This is the difference between `index.js` and text.js`. From the README:

> To match emoji in their textual representation as well (i.e. emoji that are not `Emoji_Presentation` symbols and that aren’t forced to render as emoji by a variation selector), require the `text` regex: [...]
