### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by milesj** [mathiasbynens/emoji-regex#7]
This project seems to be out of date. Any plans to update it to the latest emoji standard? If not, know of an alternative library?

**Comment by StevenTang166** [comment]
Hello, you can try this Emoji Regex, I made it, and it is currently up to date, and should remain up to date as long as the repository is updated. However, it is created in pure Javascript, and is not a Node package.

**Comment by josephrocca** [comment]
Hey @mathiasbynens, I noticed you made an update a couple of weeks ago. Was that update to support the newer emojis, or for something else? Thanks for your work on this lib!

**Comment by mathiasbynens** [comment]
@josephrocca See #8 for what changed. The regular expression was made more compact but no new emojis are being matched.

**Comment by josephrocca** [comment]
@mathiasbynens Gotcha. Up to which unicode version is currently supported? Is it difficult to add the new unicode ranges? Can I help?

**Comment by mathiasbynens** [comment]
The library has been updated now!

> Up to which unicode version is currently supported?

Trick question! Emoji can be updated independently from the Unicode version — see http://unicode.org/reports/tr51/.
