### ISSUE TITLE
Doesn't match flags like this one 🏴󠁵󠁳󠁴󠁸󠁿

### ISSUE THREAD

**Issue by jcubic** [mathiasbynens/emoji-regex#70]
When using match on flag it return default empty flag "🏴".

**Comment by mathiasbynens** [comment]
Seems to work for me:

```
$ npm install emoji-regex
$ node -p "require('emoji-regex')().exec('\u{1F3F4}')"
[ '🏴', index: 0, input: '🏴', groups: undefined ]
```

Closing until more info is provided. Please provide reproduction steps.

**Comment by jcubic** [comment]
Maybe this is bug in dev tools because if you type `['🏴󠁵󠁳󠁴󠁸󠁿']` in console it return the same flag, but if you call `'🏴󠁵󠁳󠁴󠁸󠁿'.match(re())` it returns `["🏴"]`. Not sure how to test if the flag is the same.
