### ISSUE TITLE
type defs not recognised outside of index.js

### ISSUE THREAD

**Issue by DetachHead** [mathiasbynens/emoji-regex#77]
![image](https://user-images.githubusercontent.com/57028336/103030396-72a1e680-45a7-11eb-8c0c-40990429dd14.png)

this seems to be fixable by moving the module declarations for the other js files to their own d.ts files. i will make a PR fixing this

**Comment by ben-walker** [comment]
Should this be reopened? Seems to still be an issue in the latest version, looks like the fix got moved to #80 if I'm reading things correctly.

**Comment by DetachHead** [comment]
yeah probably. i screwed up trying to fix it the first time, i didn't notice #81 never got merged

**Comment by ben-walker** [comment]
Thanks, makes sense! @mathiasbynens could this be reopened, or 81 merged?

**Comment by mathiasbynens** [comment]
#86, which includes the changes from #81, is now merged.
