### ISSUE TITLE
Certain emoji sequences are not recognized

### ISSUE THREAD

**Issue by rfgamaral** [mathiasbynens/emoji-regex#87]
I've created a CodeSandbox to better demonstrate the problem:

- https://codesandbox.io/s/bold-bouman-87fr5

If you get a blank page after loading, just click the CodeSandbox refresh button:

![image](https://user-images.githubusercontent.com/96476/109669945-8438d900-7b6a-11eb-9ab4-7ab7a51da01e.png)

The problem is copying/pasting the [infinity emoji from Emojipedia](https://emojipedia.org/infinity/) results in a detected emoji, however, copying/pasting the [infinity emoji from Emooooji](https://emooooji.com/infinity) does not detect the emoji.

The same thing happens if you input the infinity emoji through the Windows 10 Emoji Panel, the emoji is not detected.

Using `emoji-regex/es2015/text.js` instead of `emoji-regex/es2015/RGI_Emoji.js` detects the infinity emoji in all scenarios, but this regex catches more than I'd like, and I can't use it.

Is this something that can/should be fixed on this regex? Or is this something that Emooooji/Windows 10 should fix themselves?

**Comment by koculu** [comment]
Below emoji also does not match the RGI_Emoji regex. And text.js regex is problematic. Matches non-emoji character sequences.
🌤 mostly_sunny
unified : "1F324-FE0F",
non_qualified : "1F324",

**Comment by 0xdevalias** [comment]
https://github.com/mathiasbynens/emoji-regex/issues/88 seems like the same root issue as this for the 🛍  (shopping bag) emoji

**Comment by BrodaNoel** [comment]
Clearly it's not covering the new emojis in the last iOS version.
⚾️ is not covered in my end.

I forked this repo and I tried to add that ball in the unit tests, but I couldn't find a simple way to add it to the unit tests.

If you can prepare the unit tests suite to receive an array of emojis, in order to test if they are covered with the different functions, will be nice, so we can add new emojis as soon as we see that some of them are not covered.

**Comment by n3a9** [comment]
I tried some various emoji and came up with [a list](https://github.com/pineapplelol/emojify-pr-title/blob/master/emojis/blocklist.json) of emojis that aren't matched with emoji-regex in case its helpful

**Comment by mathiasbynens** [comment]
Please try v10.0.0 and report back.

**Comment by koculu** [comment]
> Please try v10.0.0 and report back.

Tested for 🌤 and it works now.
I don't have a list for other mismatches but I'm sure this will cover more emoji sequences.
Thank you.

**Comment by mathiasbynens** [comment]
Thanks for letting me know!

**Comment by n3a9** [comment]
Yes, just confirmed that all emojis are now working. Thanks so much!
