### ISSUE TITLE
typescript synthetic import

### ISSUE THREAD

**Issue by nstringham** [mathiasbynens/emoji-regex#89]
when using emoji-regex with es style imports such as
```ts
import emojiRegex from 'emoji-regex/es2015/RGI_Emoji';
```
typescript gives the following error:
```
This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.
```

looking at the [typescript documentation for default exports](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html#default-exports) it looks like
```ts
export = emojiRegex;
```
should be replaced by 
```ts
export default emojiRegex;
```
inside each `.d.ts` file
I tried making this change manually inside my node_modules folder and it seems to resolve the issue

note: this is a regression because it used to work in v9.2.0 but it doesn't work in v9.2.2

**Comment by mathiasbynens** [comment]
Does anyone wanna submit a patch?

**Comment by nstringham** [comment]
@mathiasbynens if you don't like #99 I can make a PR that only include the typescript fix.
