### ISSUE TITLE
support for modifiers/variations

### ISSUE THREAD

**Issue by tzapu** [mathiasbynens/emoji-regex#9]
hi,

is there any chance this project will support variations?

what we are using it for is to check if a text has emojis in it then wrap them with spans with the proper fonts so they work on more browsers properly (ie, edge)

because variations are not supported, it s considering them 2 characters with mixed results in various browsers (firefox sees it properly, chrome renders two characters)

cheers

**Comment by mathiasbynens** [comment]
Variations should be supported since the rewrite. Please reopen if something isn’t working for you.
