### ISSUE TITLE
.npmrc breaks local install

### ISSUE THREAD

**Issue by gilmoreorless** [mathiasbynens/emoji-regex#92]
I wanted to run some tests on my local clone of this repository. I hadn't updated it in a while, so after pulling the latest I ran `npm install`:

```sh
$ npm i
npm ERR! code E404
npm ERR! 404 Not Found - GET https://wombat-dressing-room.appspot.com/@unicode/unicode-13.0.0/-/unicode-13.0.0-1.2.0.tgz
npm ERR! 404 
npm ERR! 404  '@unicode/unicode-13.0.0@https://wombat-dressing-room.appspot.com/@unicode/unicode-13.0.0/-/unicode-13.0.0-1.2.0.tgz' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

It looks like `.npmrc` was added as part of automating publishing. But it uses an internal Google-only repository URL that prevents installing dependencies for non-Google staff.

It's easy enough to work around locally (just delete `.npmrc`), so this is more of a heads-up than a complaint. 😃

**Comment by mathiasbynens** [comment]
That wasn't intended! Fixed.
